pinry/static/js/pinry.js

I think the seemingly random order in which the tags are displayed is confusing and unexpected. Fixing it in js is rather easy though. It probably would be easy to fix it in django as well, but I don't have any experience with django.
The second change is one jslint suggested. `==` and `!=` are [a bit weird](http://stackoverflow.com/a/359509/550119).

Case insensitive sorting of tags in javascript

---

pinry/core/api.py

Fetch the submitter with a join and get all the images, thumbnails and tags in one query each. This reduces the total query count for loading 50 pins from 304 to 8 and saves roughly half the time on my machine.
See issue #85 .

Fix N+1 queries in pin loading

---

pinry/core/migrations/0001_initial.py
pinry/settings/__init__.py
pinry/users/auth/backends.py
pinry/users/migrations/0001_initial.py
requirements.txt

Django was able to sort out the migrations nicely; run `manage.py migrate --fake-initial` to tell it your database is already in the correct state.
Tests pass; haven't thoroughly stress-tested.
I had to add migrations to the `users` app because `contrib.auth` has migrations and `users` subclasses `contrib.auth.models.User`.
Closes #38, closes #88

Update to Django 1.8 and tastypie 0.12

---

pinry/static/css/pinry.css
pinry/static/js/helpers.js
pinry/templates/includes/lightbox.html
pinry/templates/includes/pins.html

This might vary depending on personal preferences, but I decided to honor newlines and to shorten links to show only the domain.
(I usually use text to signal the source website, it started as a work around for #59 but sometime I use more than one url-reference)

Improve description text rendering

---

pinry/static/js/bookmarklet.js

- show the image size on top of the preview.
- scale down the preview to view (most) of the image instead of just the center.

bookmarklet improvements to the image preview

---

pinry/templates/includes/lightbox.html
pinry/templates/includes/pins.html

When hosted on a https site (for example using nginx with reverse proxy), the site appeared "https unsafe" as it contains on each page displaying gravatar images a http link which produce a "http+https mixed content".
As gravatar support both http and https, it's better to just include image with source like "//gravatar.com/..." because it will choose http or https depending of the current protocol used for the page.

remove explicit http image for gravatar images

---

pinry/static/js/bookmarklet.js

Removing an unnecessary off-site library, as the code doesn't get more complex.
This has the nice side-effect of fixing usage on Facebook, that forbids loading jQuery from that URL.
The only functional difference from this and the original file is that it uses a `fixed` main `DIV` (instead of `absolute`) which seems easier to use on very long pages to me (as you don't need to scroll back to the top in order to see the images), the rest is translated 1:1.

Remove the need for jQuery in bookmarklet.

---

.travis.yml

This patch enables to test on Travis CI.
To enable it, we need to do follow steps.
Step 1: Sign in to https://travis-ci.org/ with GitHub account.
Step 2: Sync account.
Step 3: Activate pinry/pinry.

Add Travis CI test

---

core/api.py

This fixes an issue where the `tags` key of pins in the API response would be serialized as the string `"<map object at 0x...>". This issue would cause a `TypeError: pins.objects[i].tags.sort is not a function` on the frontend and prevent the page from loading.

Fix tags being serialized as stringified map objects

---

pinry/static/js/bookmarklet.js
pinry/static/js/pin-form.js

A simple feauture, works well with all version of pinry.
http://192.168.200.147:8000/pins/pin-form/?pin-image-url=https%3A%2F%2Fcdnb.artstation.com%2Fp%2Fassets%2Fimages%2Fimages%2F012%2F470%2F763%2Flarge%2Fdavid-noren-hillbillygys2.jpg%3F1534957770&referer=https%3A%2F%2Fwww.artstation.com%2Fartwork%2Fmrraa&description=ArtStation%20-%20Old%20northern%20rail%20station%2C%20David%20Noren

Feature: Use page title as default description

---

README.rst

This removes the reference to a demo on getpinry.com, at least until there is a working demo there.

remove reference to demo from README

---

.dockerignore
Dockerfile.autobuild

Here is a summary of modification on the Dockerfile.autobuild, which is copied from docker-pinry repository:
1. Reduce image layers 
a. by merge RUN commands as much as possible with `&&`
2. Reduce image size
a. clean up apt package list after install required packages by `rm -rf /var/lib/apt/lists/*`
b. run `pip install` with `--no-cache-dir`
c. run `pipenv install` with `--clear`
3. Make better use of docker build cache
a. copy the Pipfile* files first so `pipenv install` could be cached
a. move more frequently changed steps later in the Dockerfile, e.g. copying the source code
4. Reduce container provision time by doing collectstatic during image build

Try to optimize Docker image

---

core/templatetags/bootstrap_field.py
pinry/templates/includes/field.html

Django has some nice details in the way it renders form fields, specifically retaining the previously entered values if there's an error.
Instead of replacing field.render() with a template I've used the `attrs` argument to that method to perform the styling we need via a template filter.

Use Django's standard field rendering for User forms.

---

pinry/static/js/bookmarklet.js

Actual dependency was already removed in ddf2891480062d421b4f36bd97a23601fd87db67.

Remove references to jQuery in bookmarklet

---

.gitignore
Dockerfile.autobuild

This pull request introduces the following changes:
- Decrease Dockefile image from 1.46GB to 325MB. 
1.  Leveraging Docker Multi-Stage technique
2.  python:3.7-slim-stretch as final image
- Add Docker Data directory to gitignore

Convert Dockerfile to Multi-Stage & Update .gitignore

---

pinry/static/js/bookmarklet.js

On many websites (just as in the page generated by our bookmarklet) images are put in CSS as background images; add support for those as well.

Add bookmarklet support for background images

---

pinry-spa/src/components/Pins.vue

I originally used this patch locally for lack of "Referer" support in old Pinry, now that we have that most of my "single-link descriptions" are obsolete and should be better converted to a "Referer", but I think this can still be an useful feature to have, in case one has more than one link.
E.g. the following description:
> Monika from Doki Doki Literature Club
> https://twitter.com/lilmonix3/status/963869736596467714
> https://satchely.deviantart.com/art/Valentine-s-Monika-730977965
shows up like this:
PS: it uses `v-html` but no user-generated HTML is allowed in the description, it gets escaped properly.

Add support for links in description

---

Pipfile
Pipfile.lock
core/migrations/0001_initial.py
core/models.py
core/tests/api.py
core/tests/views.py
django_images/migrations/0001_initial.py
django_images/models.py
django_images/tests.py
docker/nginx/sites-enabled/default
docs/src/upgrade-guide.md
mkdocs.yml
pinry-spa/vue.config.js
pinry/middleware.py
pinry/settings/base.py
pinry/urls.py
users/middleware.py
users/tests.py
users/urls.py
users/views.py

Django's roadmap tells that django2 is LTS, and lastest version of django 3 is 3.0.8 currently.
So I use django 2.2 LTS instead of django 3 until django 3 has an LTS version.
ref: https://www.djangoproject.com/download/

Refactor/upgrade to django 2 LTS

---

docs/src/install-with-docker.md

In docker run command, pinry/pinry is a 3 year old image. Should be getpinry/pinry.

Update docker image name

---

docs/src/passwords.md

There is a small typo in docs/src/passwords.md.
Should read `requires` rather than `requries`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, requries -> requires

---

pinry-spa/src/components/PinPreview.vue

'Permalink' is shorter, and pretty universally recognized.

PinPreview: reword 'pin link' => 'permalink'

---

pinry-spa/src/components/PinPreview.vue
pinry-spa/src/components/Pins.vue
pinry-spa/src/components/pin_edit/PinCreateModal.vue

'Source' is more accurate, since we're talking about where the image originates, not just who referred it to us.  And include the link on the pin cards that display on boards as well, for easier access.

change 'referer' to 'source', display link on cards

---

pinry/static/js/bookmarklet.js

`display: block` is needed on some pages that have local CSS overrides that happen to apply to our elements as well.
`z-index: 2147483647` seems to be the maximum allowed values, as per http://web.archive.org/web/20160502062529/http://www.puidokas.com/max-z-index
Fixes #273.

Fix bookmarklet layout to work on more pages.

---

pinry-spa/package.json
pinry-spa/yarn.lock

Node Sass is considered deprecated - the recommended alternative is Dart Sass.
This change implements the suggested migration, as outlined at the following
URL:
https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate

Fix: Replace deprecated node-sass with sass

---

Dockerfile.autobuild

This makes `Dockerfile.autobuild` work on arm64 (and probably armhf, but I haven't tested). I have this running on an arm64 Pi4 with these changes.
`psycopg2-binary` isn't available on arm but will fall back to compiling from source so long as those missing libs are installed first. Otherwise it just breaks with "pg_config executable not found" (seems this happened since #248).
I figure if someone else like me wants an arm version they're likely to rebuild [getpinry/pinry](https://hub.docker.com/r/getpinry/pinry/) from the same Dockerfile and will benefit from this.
Hopefully this change makes sense here, rather than a separate Dockerfile; there's probably only a few steps between this and actually publishing a multiarch image to Docker Hub (or just a separate arm tagged image).

Make Dockerfile.autobuild compatible with arm

---

pinry-spa/src/components/PinPreview.vue

Fixes https://github.com/pinry/pinry/issues/343 by setting the image width to auto, and centering it in the modal window.

Don't zoom in on small images in preview window

---

pinry-spa/src/components/Pins.vue

Hello,
I noticed that "Source" link always shows in a pin description, even if no source is defined.
My change hides the "Source" part when the source/referer is empty.

Do not show Source link when no source is defined

---

pinry-spa/src/components/Pins.vue

Looks like the pin image's alt attribute is meant to come from the item description, but isn't using the bind syntax, so all images have the "item.description" as the alt text currently.

Fix unbound image alt attribute
